gitlab:
  image: gitlab/gitlab-ce:latest
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com:10080'
      mattermost_external_url 'http://mattermost.example.com:10080'
#      registry_external_url 'https://registry.gitlab.example.com'
#      gitlab_rails['registry_enabled']  true
#      gitlab_rails['registry_host']  "registry.gitlab.example.com"
#      gitlab_rails['registry_port']  "5005"
#      gitlab_rails['registry_api_url']  "http://localhost:5000"
#      gitlab_rails['registry_key_path']  "/var/opt/gitlab/gitlab-rails/certificate.key"
#      gitlab_rails['registry_path']  "/var/opt/gitlab/gitlab-rails/shared/registry"
#      gitlab_rails['registry_issuer']  "omnibus-gitlab-issuer"

  volumes:
    - /srv/gitlab/config:/etc/gitlab
    - /srv/gitlab/logs:/var/log/gitlab
    - /srv/gitlab/data:/var/opt/gitlab
  ports:
    - "10080:10080"
#    - "5005:5005"
#    - "5000:5000"
    - "10022:22"
    - "10443:443"
  restart: always
