- name: Rancher module
  hosts: Rancher-host
  become: True
  tasks:
    - name: 'Setup Rancher'
      rancher:
        url: 'http://188.166.50.73:8080'
        access_key: 'B74C6ABF27515D372720'
        secret_key: 'xcj8UYFYz1JuKNyTUYK4iUxX7mWog2H1V1dEQ23v'
        catalogs:
          - url: 'https://github.com/manishjindal/rancher-cattle-demo.git'
            name: 'MyCatalog'
            branch: 'master'
        environments:
          - name: Production
            stacks:
              - name: Janitor
                catalog_entry: 'MyCatalog:Janitor'
    - name: 'Display Registration Token'
      debug:
        msg: "Rancher Production Token is {{ rancher.envs.Production.token }}"
