- name: 'Rancher module'
  hosts: Rancher-master
  #hosts: localhost
  #connection: local
  #gather_facts: yes
  tasks:
    - name: install stack
      rancher_compose:
        docker_compose: "/root/Rancher-Ansible/stacks/artifactory/docker-compose.yml"
        url: http://139.59.41.99:8080
        access_key: A33E8A308E51681CE5B7
        secret_key: LMWe5HjAdC4vgVAMrDRfBdsgwRujr9aJaEJa9i2E
        project_name: artifactory-stack
        state: started
