---
- name: Installing and configuring Docker
  hosts: all
  become: yes
  vars_files:
    - providers/other/vars/other_vars.yml
  roles:
    - { role: docker, tags: ["docker"] }

- name: Setting up Rancher Server
  hosts: Rancher-master
  vars_files:
    - providers/other/vars/other_vars.yml
  become: yes
  roles:
    - { role: rancher, tags: ["rancher"] }

- name: Register Rancher Hosts
  hosts: Rancher-host
  become: yes
  vars_files:
    - providers/other/vars/other_vars.yml
  roles:
    - { role: rancher_reg, tags: ["rancher_reg"] }
