---
- name: Restart Docker Postgres
  docker:
    name: '{{ docker_postgres_name }}'
    image: '{{ docker_postgres_image }}'
    hostname: '{{ docker_postgres_hostname }}'
    env: '{{ docker_postgres_env }}'
    ports: '{{ docker_postgres_ports }}'
    volumes: '{{ docker_postgres_volumes }}'
    state: started
    #restart: True
