mysql:
  image: mysql:latest
  container_name: mysql
  environment:
      MYSQL_ROOT_PASSWORD: password
redis:
  image: redis:latest
  container_name: redis
web:
  image: mjindal/myflaskapp7:latest
  ports:
   - "5000:5000"
  links:
   - redis:redis
   - mysql:mysql

