# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#       ____              ____            __  
#      / __ \__  ______  / __ \___  _____/ /__
#     / /_/ / / / / __ \/ / / / _ \/ ___/ //_/
#    / _, _/ /_/ / / / / /_/ /  __/ /__/ ,<   
#   /_/ |_|\__,_/_/ /_/_____/\___/\___/_/|_|  
#                                             
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

version: '2'

services:
  rundeckmysql:
    restart: always
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: rundeck
     # The following must match the DB_USER and DB_PASSWORD values passed to Rundeck
       MYSQL_USER: rundeck
       MYSQL_PASSWORD: user
       MYSQL_ROOT_PASSWORD: password 
    volumes:
      - /data/rundeck/var/lib/mysql:/var/lib/mysql

  rundeck:
    depends_on:
      - rundeckmysql
    restart: always
    image: jordan/rundeck:2.7.1
    ports:
      - "0.0.0.0:4440:4440"
    links:
      - rundeckmysql
    environment:
       DATABASE_URL: "jdbc:mysql://rundeckmysql/rundeck?autoReconnect=true"
       RUNDECK_PASSWORD: user
       RUNDECK_ADMIN_PASSWORD: admin
       NO_LOCAL_MYSQL: 'true'
      # RUNDECK_WITH_SSL: 'false'
       EXTERNAL_SERVER_URL: ''
    volumes:
      - /data/rundeck/var/rundeck/projects:/var/rundeck/projects:rw
      - /data/rundeck/var/lib/keys:/var/lib/rundeck_ssh:ro
      - /data/rundeck/var/logs/rundeck:/var/log/rundeck:rw
      - /data/rundeck/etc/rundeck:/etc/rundeck:rw

