gitlab:
  image: gitlab/gitlab-ce:latest
  environment:
    hostname: gitlab.example.com

  volumes:
    - /srv/gitlab/config:/etc/gitlab
    - /srv/gitlab/logs:/var/log/gitlab
    - /srv/gitlab/data:/var/opt/gitlab
  ports:
    - "80:80"
    - "522:22"
    - "443:443"
  restart: always
