---
docker_artifactory_name: 'artifactory'
docker_artifactory_image: 'docker.bintray.io/jfrog/artifactory-pro:latest'
docker_artifactory_hostname: '174.138.6.24'
docker_artifactory_data_directories:
  - '/test/docker/artifactory'
docker_artifactory_volumes:
  - '/test/docker/artifactory:/var/opt/jfrog/artifactory'
docker_artifactory_ports: '8081:8081'
docker_artifactory_env:
  DB_TYPE: 'postgresql'
  DB_HOST: '165.227.9.29'
  DB_PORT: '5432'
  DB_USER: 'artifactory'
  DB_PASSWORD: 'artifactory'
  #Add extra Java options by uncommenting the following line
  #- EXTRA_JAVA_OPTIONS=Xmx4g
