postgres:
  image: postgres:latest
  container_name: postgres
  environment:
      POSTGRES_USER: "artifactory"
      POSTGRES_PASSWORD: "artifactory"
  ports:
   - "5433:5432"
  #volumes:
  # - "/project/docker/postgres:/var/lib/postgresql/data"
  restart: always

artifactory:
  image: docker.bintray.io/jfrog/artifactory-pro:latest
  environment:
      DB_TYPE: "postgresql"
      DB_HOST: "159.89.172.39"
      DB_PORT: "5433"
      DB_USER: "artifactory"
      DB_PASSWORD: "artifactory"
  #    EXTRA_JAVA_OPTIONS: "Xmx1g"
  ports:
   - "8081:8081"
  #volumes:
  # - "/test/docker/artifactory:/var/opt/jfrog/artifactory"
  #links:
  # - postgres
  restart: always
