---

- name: Install dependencies
  yum:
      name={{ item }}
      update_cache=yes
      state=present
  with_items: "{{ __docker_pre_packages }}"

- name: Install pip
  easy_install:
      name=pip

- name: Install docker-py
  pip:
    name: docker-py
    state: present

- name: Add docker yum repo
  shell: "yum-config-manager --add-repo {{ __docker_repo_url }}"
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: __docker_package == "docker-ce"


- name: Install Docker package
  yum:
    name: "{{ __docker_package }}"
    #name: "{{ __docker_package }}-{{ __docker_version }}"
    state: present
  notify: restart docker
